#!/bin/bash
# JishuShell Hermes entrypoint shim.
# Wraps ghcr.io/x-aijishu/hermes-runtime:latest for per-instance upgrades.
#
# Business logic mirrors OpenClaw's update-seed pattern
# (src/services/runtime/adapters/openclaw.ts:ensureOpenclawUpdateSeed):
#   1. Baseline runtime is baked into the image (/opt/hermes).
#   2. A persistent venv lives on the bind-mounted agent-home
#      (${HERMES_HOME}/.venv) and is seeded from the image on first boot.
#   3. In-container `uv pip install --upgrade ...` writes to the persistent
#      venv, so after `docker restart` the instance boots the upgraded
#      version — exactly like `npm install openclaw@latest` on OpenClaw.
#
# Implements §32.1 decisions from docs/multi-agent-runtime-generalization-plan.md:
#   §32.1.2 — incomplete venv recovery via .installed-ref sentinel
#   §32.1.3 — baseline mode detected by ABSENCE of JISHUSHELL_HERMES_SOURCE_REF env,
#              not by any literal "image-baseline" string
set -e

IMAGE_INSTALL_DIR=/opt/hermes
IMAGE_VENV_DIR=/opt/hermes/.venv
HERMES_HOME=/opt/data
PERSISTENT_VENV_DIR=/opt/data/.venv
OVERLAY_DIR=/opt/data/hermes-overlay

# ── UID/GID remap (keep bind-mount permissions controllable) ──────────────────
if [ "$(id -u)" = "0" ]; then
  if [ -n "$HERMES_UID" ] && [ "$HERMES_UID" != "$(id -u hermes)" ]; then
    echo "[jishushell-shim] remapping hermes uid → $HERMES_UID"
    usermod -u "$HERMES_UID" hermes
  fi
  if [ -n "$HERMES_GID" ] && [ "$HERMES_GID" != "$(id -g hermes)" ]; then
    echo "[jishushell-shim] remapping hermes gid → $HERMES_GID"
    groupmod -g "$HERMES_GID" hermes
  fi
  chown -R hermes:hermes "$HERMES_HOME"
  # Re-exec under hermes user. Use `bash "$0"` instead of `"$0"` directly —
  # Nomad/Docker bind-mounts sometimes drop the exec bit, so execve on the
  # shim file fails with EACCES. Invoking bash as the interpreter bypasses
  # that check entirely (bash reads the file, no execve on the script).
  exec gosu hermes bash "$0" "$@"
fi

# ── Mode selection (§32.1.3): overlay requires BOTH non-empty SOURCE_REF AND
#    the overlay source pyproject.toml to exist; no "image-baseline" sentinel ──
if [ -n "$JISHUSHELL_HERMES_SOURCE_REF" ] && [ -f "$OVERLAY_DIR/source/pyproject.toml" ]; then
  # ── overlay mode: use per-instance upgraded version ──────────────────────
  echo "[jishushell-shim] overlay mode (ref=$JISHUSHELL_HERMES_SOURCE_REF)"
  INSTALL_DIR="$OVERLAY_DIR/source"
  VENV_DIR="$OVERLAY_DIR/.venv"

  # §32.1.2: incomplete venv recovery — venv dir exists but sentinel missing
  if [ -d "$VENV_DIR" ] && [ ! -f "$VENV_DIR/.installed-ref" ]; then
    echo "[jishushell-shim] incomplete venv detected, rebuilding"
    rm -rf "$VENV_DIR"
  fi

  INSTALLED_REF=$(cat "$VENV_DIR/.installed-ref" 2>/dev/null || echo "")

  if [ ! -f "$VENV_DIR/bin/activate" ] || [ "$JISHUSHELL_HERMES_SOURCE_REF" != "$INSTALLED_REF" ]; then
    echo "[jishushell-shim] building overlay venv from source @ $JISHUSHELL_HERMES_SOURCE_REF (one-time per upgrade, ~1-3 min)..."
    rm -rf "$VENV_DIR"
    cd "$INSTALL_DIR"
    uv venv "$VENV_DIR"
    uv pip install --no-cache-dir --python "$VENV_DIR/bin/python" -e ".[all]"
    echo "$JISHUSHELL_HERMES_SOURCE_REF" > "$VENV_DIR/.installed-ref"
    echo "[jishushell-shim] overlay venv ready."
  fi
else
  # ── baseline mode: image venv (fast first boot) → persistent venv on upgrade ──
  #
  # Mirrors OpenClaw's update-seed model:
  #   - First boot: $PERSISTENT_VENV_DIR is missing, activate image venv
  #     directly (zero-overhead startup — no copy, no rebuild).
  #   - After user runs the in-container upgrade helper below, the
  #     persistent venv lives on the bind-mounted agent-home, so future
  #     boots pick it up and the user's upgraded packages survive
  #     container restart.
  INSTALL_DIR="$IMAGE_INSTALL_DIR"
  if [ -d "$PERSISTENT_VENV_DIR" ]; then
    VENV_DIR="$PERSISTENT_VENV_DIR"
    echo "[jishushell-shim] baseline (persistent venv — in-container upgrades active)"
  else
    VENV_DIR="$IMAGE_VENV_DIR"
    echo "[jishushell-shim] baseline (image venv — fast first boot)"
  fi
fi

# ── Deploy the upgrade helper (idempotent) ──────────────────────────────────
# Gives users a one-command upgrade path:
#     docker exec -it <container> /opt/data/jishushell-hermes-upgrade [pkg-spec]
# mirroring OpenClaw's "Update now" button. Writes into the bind-mounted
# agent-home so it persists without touching the image.
UPGRADE_HELPER="$HERMES_HOME/jishushell-hermes-upgrade"
cat > "$UPGRADE_HELPER" <<'HELPER'
#!/bin/bash
# In-container Hermes upgrade helper (auto-generated by jishushell shim).
#
# Privilege model — never escalate:
#   - If invoked as root (e.g. plain `docker exec`), re-exec under the
#     hermes service account via gosu. All writes go through the unprivileged
#     user so files on the mounted volume end up with hermes:hermes
#     ownership, matching the service that actually runs the agent.
#   - All filesystem writes stay inside the bind-mounted /opt/data volume.
#     The read-only image layers at /opt/hermes are never touched.
#
# First run: seeds persistent venv from image baseline (~5-10s cp + sed).
# Subsequent runs: fast (venv already persistent).
# Restart the container after running to load the upgraded version.
set -e

if [ "$(id -u)" = "0" ]; then
  exec gosu hermes bash "$0" "$@"
fi

TARGET="${1:-hermes-agent}"
IMAGE_VENV=/opt/hermes/.venv
PERSISTENT_VENV=/opt/data/.venv

if [ ! -d "$PERSISTENT_VENV" ]; then
  echo "[jishushell-upgrade] seeding persistent venv from image baseline ..."
  cp -r "$IMAGE_VENV" "$PERSISTENT_VENV"
  # Rewrite hardcoded paths so the copied venv's entrypoints resolve to
  # the persistent location, not back to the read-only image path.
  find "$PERSISTENT_VENV/bin" -type f -exec \
    sed -i "s|$IMAGE_VENV|$PERSISTENT_VENV|g" {} + 2>/dev/null || true
  [ -f "$PERSISTENT_VENV/pyvenv.cfg" ] && \
    sed -i "s|$IMAGE_VENV|$PERSISTENT_VENV|g" "$PERSISTENT_VENV/pyvenv.cfg" || true
  echo "[jishushell-upgrade] seed complete."
fi

source "$PERSISTENT_VENV/bin/activate"
# uv-created venvs don't ship pip; bootstrap it on demand. ensurepip is a
# stdlib module so this works on every Python >= 3.4 without network.
python -m ensurepip --upgrade >/dev/null 2>&1 || true
echo "[jishushell-upgrade] python -m pip install --upgrade $TARGET ..."
python -m pip install --upgrade "$TARGET"
echo "[jishushell-upgrade] done. Restart the container to load the upgraded version:"
echo "                    docker restart <container-id>  (or panel: Restart button)"
HELPER
chmod 755 "$UPGRADE_HELPER"

# ── Config bootstrap (both modes): mkdir + copy examples when missing ────────
mkdir -p "$HERMES_HOME"/{cron,sessions,logs,hooks,memories,skills,skins,plans,workspace,home}
[ -f "$HERMES_HOME/.env" ]        || cp "$INSTALL_DIR/.env.example"            "$HERMES_HOME/.env"
[ -f "$HERMES_HOME/config.yaml" ] || cp "$INSTALL_DIR/cli-config.yaml.example" "$HERMES_HOME/config.yaml"
[ -f "$HERMES_HOME/SOUL.md" ]     || cp "$INSTALL_DIR/docker/SOUL.md"          "$HERMES_HOME/SOUL.md"

# ── Skills sync (best-effort, upstream behavior) ─────────────────────────────
python3 "$INSTALL_DIR/tools/skills_sync.py" || true

# ── Activate venv and hand off to hermes ─────────────────────────────────────
source "$VENV_DIR/bin/activate"
exec hermes "$@"
